/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

projectId=project
datasetProjectId=datasetProject
referenceName=referenceName
table=table
tableKey=relationTableKey
clusterOrder=clusteringOrder
dataset=dataset
skipHeader=switch-skipHeader
path=path
name=name
truncateTable=switch-truncateTable
truncateTableMacroInput=truncateTable
updateTableSchema=switch-allowSchemaRelaxation
updateTableSchemaMacroInput=allowSchemaRelaxation
format=select-format
formatMacroInput=format
requirePartitionFilter=switch-requirePartitionField
requirePartitionFilterMacroInput=requirePartitionField
partitioningType=partitioningType
partitionStartDate=partitionFrom
partitionEndDate=partitionTo
filter=filter
instanceId=instance
databaseName=database
tableName=table
sql=sql
jobLocation=location
storeResultsInBigQueryTable=switch-storeResults
rowAsArguments=switch-rowAsArguments
serviceAccountType=serviceAccountType
serviceAccountFilePath=serviceFilePath
serviceAccountJSON=serviceAccountJSON
outputSchemaMacroInput=Output Schema-macro-input
flexibleSchema=switch-allowFlexibleSchema
updateSchema=allowSchemaRelaxation

## CONNECTION-MANAGEMENT-START
connection=connection
useConnection=switch-useConnection
addConnection=add-connection-button
gcsConnectionRow=connector-GCS
bqConnectionRow=connector-BigQuery
spannerConnectionRow=connector-Spanner
testConnection=connection-test-button
connectionCreate=connection-submit-button
parsingOptionConfirm=parsing-config-confirm
## CONNECTION-MANAGEMENT-END
